# Generated by Django 4.2.7 on 2023-11-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUnit',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[(1, 'OFFER'), (2, 'CATEGORY')], max_length=100)),
                ('price', models.BigIntegerField(blank=True, default=None, null=True)),
                ('parentId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shopunit')),
            ],
        ),
    ]
