# Generated by Django 4.2.7 on 2023-11-26 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_shopunit_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='parentId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shopunit'),
        ),
    ]
